# Generated by Django 3.2.7 on 2021-10-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_auto_20211001_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarmodel',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='navbarmodel',
            name='category_url',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navbarmodel',
            name='categories',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.navbarmodel'),
            preserve_default=False,
        ),
    ]
