# Generated by Django 3.2.7 on 2021-10-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_rename_subcategories_category_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
    ]
