# Generated by Django 3.2.7 on 2021-10-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_auto_20211003_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='collection_title',
            new_name='collection_text',
        ),
    ]
