# Generated by Django 3.2.7 on 2021-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_rename_collection_title_settings_collection_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='brand_images',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='latest_blog_images',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='redcard_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
    ]
