# Generated by Django 3.2.7 on 2021-10-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_auto_20211003_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
