# Generated by Django 3.2.7 on 2021-10-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_auto_20211003_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel_2',
            new_name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductModel_1',
        ),
    ]
