# Generated by Django 3.2.7 on 2021-10-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_auto_20211003_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel_1',
            new_name='ProductModel1',
        ),
        migrations.RenameModel(
            old_name='ProductModel_2',
            new_name='ProductModel2',
        ),
    ]
