# Generated by Django 3.2.7 on 2021-10-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_contactdetailsmodel_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('sub_categories', models.BooleanField(default=False)),
                ('navbar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.navbarmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.categorymodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='ProductModel1',
        ),
        migrations.DeleteModel(
            name='ProductModel2',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='subcategory_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.subcategorymodel'),
        ),
    ]
