# Generated by Django 3.2.7 on 2021-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel2',
            new_name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductModel1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='price',
            new_name='price_1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='price_2',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='price_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='price_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='price_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
