# Generated by Django 3.2.7 on 2021-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0015_auto_20211009_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='sub_categories',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='navbar_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
        migrations.DeleteModel(
            name='SubCategoryModel',
        ),
    ]
