# Generated by Django 3.2.7 on 2021-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0016_auto_20211009_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='navbar_id',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='navbar_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
    ]
