# Generated by Django 3.2.6 on 2021-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0018_auto_20211016_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('navbar_id', models.ManyToManyField(to='ecom_app.NavbarModel')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='ClientBrand',
        ),
        migrations.DeleteModel(
            name='ElectronicsProduct',
        ),
        migrations.DeleteModel(
            name='Latest_Blog',
        ),
        migrations.DeleteModel(
            name='MenProduct',
        ),
        migrations.DeleteModel(
            name='RedCard',
        ),
        migrations.DeleteModel(
            name='SportsProduct',
        ),
        migrations.DeleteModel(
            name='WomenProduct',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='settings',
            name='brand_images',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='latest_blog_images',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='latest_blog_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_name',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_text',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category_id',
            field=models.ManyToManyField(to='ecom_app.CategoryModel'),
        ),
    ]
