# Generated by Django 3.2.6 on 2021-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0019_auto_20211016_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=255, null=True)),
                ('price_1', models.CharField(blank=True, max_length=255, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('title_2', models.CharField(blank=True, max_length=255, null=True)),
                ('price_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('title_3', models.CharField(blank=True, max_length=255, null=True)),
                ('price_3', models.CharField(blank=True, max_length=255, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('title_4', models.CharField(blank=True, max_length=255, null=True)),
                ('price_4', models.CharField(blank=True, max_length=255, null=True)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('title_5', models.CharField(blank=True, max_length=255, null=True)),
                ('price_5', models.CharField(blank=True, max_length=255, null=True)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='Latest_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='WomenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
    ]
