# Generated by Django 3.2.7 on 2021-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0019_latest_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
            ],
        ),
    ]
