# Generated by Django 3.2.7 on 2021-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0021_auto_20211005_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
