# Generated by Django 3.2.7 on 2021-10-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0022_auto_20211005_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categories',
        ),
    ]
