# Generated by Django 3.2.7 on 2021-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0023_remove_category_sub_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
