# Generated by Django 3.2.6 on 2021-11-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0021_categorymodel_sub_categories'),
        ('ecom_app', '0024_auto_20211005_1157'),
    ]

    operations = [
    ]
