# Generated by Django 3.2.7 on 2021-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0024_auto_20211005_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
    ]
