# Generated by Django 3.2.7 on 2021-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0026_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.BooleanField(default=False),
        ),
    ]
