# Generated by Django 3.2.7 on 2021-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0029_rename_category_id_category_navbar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='navbar_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
    ]
