# Generated by Django 3.2.7 on 2021-10-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0030_auto_20211016_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category_id',
        ),
    ]
