# Generated by Django 3.2.7 on 2021-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0031_remove_productmodel_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
