# Generated by Django 3.2.7 on 2021-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0032_productmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menproduct',
            name='name_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
