# Generated by Django 3.2.7 on 2021-10-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0034_auto_20211030_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog_products',
            name='related_navbar',
        ),
        migrations.AddField(
            model_name='catalog_products',
            name='related_navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='ecom_app.navbarmodel'),
        ),
    ]
