# Generated by Django 3.2.7 on 2021-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0039_alter_latest_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_products',
            name='alternative_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='catalog_products',
            name='alternative_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='catalog_products',
            name='alternative_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
    ]
