# Generated by Django 3.2.7 on 2021-10-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0040_auto_20211031_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog_products',
            name='alternative_image_1',
        ),
        migrations.RemoveField(
            model_name='catalog_products',
            name='alternative_image_2',
        ),
        migrations.RemoveField(
            model_name='catalog_products',
            name='alternative_image_3',
        ),
    ]
