# Generated by Django 3.2.7 on 2021-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0042_auto_20211031_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_products',
            name='avilability',
            field=models.TextField(blank=True, choices=[('In stock', 'I'), ('Sold Out!', 'S')], null=True),
        ),
    ]
