# Generated by Django 3.2.7 on 2021-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0043_catalog_products_avilability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_products',
            name='avilability',
            field=models.TextField(blank=True, choices=[('In stock', 'In Stock'), ('Sold Out!', 'Sold Out')], null=True),
        ),
    ]
