# Generated by Django 3.2.7 on 2021-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0044_alter_catalog_products_avilability'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_products',
            name='color',
            field=models.CharField(blank=True, choices=[('pink', 'Pink'), ('black', 'Black'), ('white', 'White'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=100, null=True),
        ),
    ]
