# Generated by Django 3.2.7 on 2021-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0045_catalog_products_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_palette', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='catalog_products',
            name='color',
        ),
        migrations.AddField(
            model_name='catalog_products',
            name='color',
            field=models.ManyToManyField(to='ecom_app.colors'),
        ),
    ]
