# Generated by Django 3.2.7 on 2021-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0047_auto_20211031_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_products',
            name='del_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
