# Generated by Django 3.2.7 on 2021-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0048_catalog_products_del_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url_1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_4',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_5',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
