# Generated by Django 3.2.7 on 2021-10-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0049_auto_20211031_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_blog',
            name='url',
        ),
    ]
