# Generated by Django 3.2.7 on 2021-10-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0050_remove_latest_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='page_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ecom_app.navbarmodel'),
        ),
    ]
