# Generated by Django 3.2.7 on 2021-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0051_settings_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='sub_title',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='url',
        ),
        migrations.AddField(
            model_name='footer',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
