# Generated by Django 3.2.7 on 2021-11-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0052_auto_20211101_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='header',
        ),
        migrations.AddField(
            model_name='footer',
            name='related_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.footer_header'),
        ),
    ]
