# Generated by Django 3.2.7 on 2021-11-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0053_auto_20211101_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer_Header',
            new_name='FooterHeader',
        ),
    ]
