# Generated by Django 3.2.7 on 2021-11-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0055_alter_latest_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_blog',
            name='image',
            field=models.ImageField(default='WhatsApp_Image_2021-10-20_at_11.38.22_sOkAQwi.jpeg', upload_to='shop_images'),
        ),
    ]
