# Generated by Django 3.2.7 on 2021-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0056_alter_latest_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_blog',
            name='image',
            field=models.ImageField(default='miles.jpg', upload_to='shop_images'),
        ),
    ]
