# Generated by Django 3.2.7 on 2021-11-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0059_auto_20211106_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_products',
            name='related_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category'),
        ),
    ]
