# Generated by Django 3.2.7 on 2021-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0061_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_review', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('your_rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='catalog_products',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
