# Generated by Django 3.2.7 on 2021-11-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0062_auto_20211128_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='your_rating',
        ),
    ]
